### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider androidx.camera.camera2.impl.Camera2Initializer: java.lang.NumberFormatException: For input string: "/dev/video0"

### ISSUE THREAD

**Issue by imistyrain** [jiuqiant/mediapipe_face_detection_aar_example#2]
Process: com.example.myfacedetectionapp, PID: 10211
    java.lang.RuntimeException: Unable to get provider androidx.camera.camera2.impl.Camera2Initializer: java.lang.NumberFormatException: For input string: "/dev/video0"
        at android.app.ActivityThread.installProvider(ActivityThread.java:6445)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5987)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NumberFormatException: For input string: "/dev/video0"
        at java.lang.Integer.parseInt(Integer.java:604)
        at java.lang.Integer.parseInt(Integer.java:650)
        at androidx.camera.camera2.impl.SupportedSurfaceCombination.getRecordSize(SupportedSurfaceCombination.java:1108)
        at androidx.camera.camera2.impl.SupportedSurfaceCombination.generateSurfaceSizeDefinition(SupportedSurfaceCombination.java:1068)
        at androidx.camera.camera2.impl.SupportedSurfaceCombination.init(SupportedSurfaceCombination.java:671)
        at androidx.camera.camera2.impl.SupportedSurfaceCombination.<init>(SupportedSurfaceCombination.java:95)
        at androidx.camera.camera2.impl.Camera2DeviceSurfaceManager.init(Camera2DeviceSurfaceManager.java:192)
        at androidx.camera.camera2.impl.Camera2DeviceSurfaceManager.<init>(Camera2DeviceSurfaceManager.java:64)
        at androidx.camera.camera2.Camera2AppConfig.create(Camera2AppConfig.java:58)
        at androidx.camera.camera2.impl.Camera2Initializer.onCreate(Camera2Initializer.java:45)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1920)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1895)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6440)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5987) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mmaSunshine** [comment]
@imistyrain hello ,Have you solved this problem？ I have the same problem

**Comment by wwdok** [comment]
I  am facing this issue too...

**Comment by Hatzen** [comment]
On which devices are u facing the problem?  
It looks like the device "/dev/video0" is not accessible.   
Probably your are testing with emulator without a camera setup or a uncommon device with multiple cameras and video decoders?
